package doekaschi.boirebirthwiki;

import android.annotation.TargetApi;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Build;
import android.preference.PreferenceManager;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;


public class passiveItems extends ActionBarActivity {

    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_passive_items);
        setTitle("Passive Collectibles");
        int currentApi= Build.VERSION.SDK_INT;
        if(currentApi>=21) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            getWindow().setStatusBarColor(getResources().getColor(R.color.status_background));
        };
        ListView lv=(ListView) findViewById(R.id.listPassive);
        final String items[] = new String[] {
                "<3",
                "???'s Only Friend",
                "1up!",
                "20/20",
                "3 Dollar Bill",
                "9 Volt",
                "Abaddon",
                "Abel",
                "Anemic",
                "Ankh",
                "Anti-Gravity",
                "Aquarius",
                "Aries",
                "Ball Of Bandages",
                "Ball Of Tar",
                "The Battery",
                "The Belt",
                "Best Bud",
                "BFFS!",
                "BBF",
                "Big Fan",
                "The Black Bean",
                "Black Candle",
                "Black Lotus",
                "Blood Bag",
                "Blood Clot",
                "Blood Of The Martyr",
                "Bloody Lust",
                "Blue Cap",
                "Blue Map",
                "Bob's Brain",
                "Bob's Curse",
                "Bobby-Bomb",
                "The Body",
                "Bogo Bombs",
                "Bomb Bag",
                "Boom!",
                "Box",
                "Breakfast",
                "Brimstone",
                "Broken Watch",
                "Brother Bobby",
                "Bucket Of Lard",
                "Bum Friend",
                "Butt Bombs",
                "Caffeine Pill",
                "Cain's Other Eye",
                "Cancer",
                "Capricorn",
                "Cat-O-Nine-Tails",
                "Celtic Cross",
                "Ceremonial Robes",
                "Champion Belt",
                "Charm Of The Vampire",
                "Chemical Peel",
                "Chocolate Milk",
                "The Common Cold",
                "The Compass",
                "Contract From Below",
                "Cricket's Body",
                "Cricket's Head",
                "Cube Of Meat",
                "Cupid's Arrow",
                "Cursed Eye",
                "Daddy Longlegs",
                "Dark Bum",
                "Dark Matter",
                "Dead Bird",
                "Dead Cat",
                "Dead Dove",
                "Dead Onion",
                "Death's Touch",
                "Demon Baby",
                "Dessert",
                "Dinner",
                "Distant Admiration",
                "A Dollar",
                "Dr. Fetus",
                "Dry Baby",
                "E Coli",
                "Epic Fetus",
                "Eve's Mascara",
                "Experimental Treatment",
                "Fanny Pack",
                "Fate",
                "Fire Mind",
                "Forever Alone",
                "Gemini",
                "Ghost Baby",
                "Gimpy",
                "Gnawed Leaf",
                "Goat Head",
                "Godhead",
                "Growth Hormones",
                "Guardian Angel",
                "Guillotine",
                "Guppy's Collar",
                "Guppy's Hair Ball",
                "Guppy's Tail",
                "Habit",
                "The Halo",
                "Halo Of Flies",
                "Harlequin Baby",
                "Headless Baby",
                "Hive Mind",
                "Holy Grail",
                "Holy Mantle",
                "Holy Water",
                "Hot Bombs",
                "Humbling Bundle",
                "Infamy",
                "Infestation",
                "Infestation 2",
                "The Inner Eye",
                "Ipecac",
                "Iron Bar",
                "Isaac's Heart",
                "Jesus Juice",
                "Judas' Shadow",
                "Juicy Sack",
                "Key Piece 1",
                "Key Piece 2",
                "The Ladder",
                "Latch Key",
                "Lazarus' Rags",
                "Leech",
                "Leo",
                "Libra",
                "Lil' Brimstone",
                "Lil' Haunt",
                "Little Baggy",
                "Little C.H.A.D.",
                "Little Chubby",
                "Little Gish",
                "Little Steven",
                "Loki's Horns",
                "Lord Of The Pit",
                "Lost Contact",
                "Lucky Foot",
                "The Ludovico Technique",
                "A Lump Of Coal",
                "Lunch",
                "Maggy's Bow",
                "Magic 8 Ball",
                "Magic Mushroom",
                "Magic Scab",
                "Magneto",
                "The Mark",
                "Match Book",
                "MEAT!",
                "Midas' Touch",
                "The Mind",
                "Mini Mush",
                "Missing Page 2",
                "Missing No.",
                "Mitre",
                "Mom's Coin Purse",
                "Mom's Contacts",
                "Mom's Eye",
                "Mom's Eyeshadow",
                "Mom's Heels",
                "Mom's Key",
                "Mom's Knife",
                "Mom's Lipstick",
                "Mom's Perfume",
                "Mom's Purse",
                "Mom's Underwear",
                "Mom's Wig",
                "Money = Power",
                "Mongo Baby",
                "Monstro's Lung",
                "Mr. Mega",
                "The Mulligan",
                "Mutant Spider",
                "My Reflection",
                "Mysterious Liquid",
                "Mystery Sack",
                "Number One",
                "Odd Mushroom (Large)",
                "Odd Mushroom (Thin)",
                "Old Bandage",
                "Ouija Board",
                "The Pact",
                "Pageant Boy",
                "The Parasite",
                "The Peeper",
                "Pentagram",
                "PHD",
                "Pisces",
                "Piggy Bank",
                "Placenta",
                "Polyphemus",
                "Proptosis",
                "Punching Bag",
                "Pyro",
                "Pyromaniac",
                "A Quarter",
                "Rainbow Baby",
                "Raw Liver",
                "The Relic",
                "Robo-Baby",
                "Robo-Baby 2.0",
                "Roid Rage",
                "Rosary",
                "Rotten Baby",
                "Rotten Meat",
                "Rubber Cement",
                "Sack Of Pennies",
                "Sacred Heart",
                "Sacrificial Dagger",
                "Sad Bombs",
                "The Sad Onion",
                "Safety Pin",
                "Sagittarius",
                "Samson's Chains",
                "Scapular",
                "Scorpio",
                "Screw",
                "Sharp Plug",
                "Sissy Longlegs",
                "Sister Maggy",
                "Skatole",
                "Skeleton Key",
                "The Small Rock",
                "Smart Fly",
                "SMB Super Fan!",
                "A Snack",
                "Soy Milk",
                "The Soul",
                "Speed Ball",
                "Spelunker Hat",
                "Spider Bite",
                "Spider Baby",
                "Spirit Of The Night",
                "Spoon Bender",
                "Squeezy",
                "Starter Deck",
                "Steam Sale",
                "Stem Cells",
                "Steven",
                "Stigmata",
                "Stop Watch",
                "Strange Attractor",
                "Super Bandage",
                "Synthoil",
                "Taurus",
                "Tech.5",
                "Technology",
                "Technology 2",
                "Tiny Planet",
                "The Negative",
                "The Polaroid",
                "There's Options",
                "Thunder Thighs",
                "Toothpicks",
                "Torn Photo",
                "Tough Love",
                "Transcendence",
                "Treasure Map",
                "Trinity Shield",
                "The Wafer",
                "Whore Of Babylon",
                "Wire Coat Hanger",
                "Wooden Spoon",
                "Virgo",
                "The Virus",
                "X-Ray Vision",
        };

        final String[] effects=new String[] {"Increases available heart containers by 1 and restores all health.",
                "Summons a big attack fly that can be controlled with the shooting direction-keys.",
                "Gives an extra life. Upon death, you will respawn in the previous room with full health and lose the 1up!.",
                "Grants a double shot.",
                "Gives Isaac a random tear effect every room. Effect given changes upon entering a room.",
                "Reduces the charge of any Activated Items by 1. Any 1 charge items instead have timed recharges.",
                "Increases damage and speed, removes all red heart containers, grants six black hearts, and adds a chance to shoot fear tears.",
                "A familiar that mirrors the player's movements and shoots in the opposite direction.",
                "+5 Range. After Isaac is damaged, a trail of red creep will be left behind Isaac until he leaves the current room.",
                "Upon death, the player will respawn as Blue Baby with 3 Soul Hearts.",
                "Tears up. Tears float in position until firing ceases, after which they will fly off in the direction they were shot in.",
                "A trail of creep tears are left behind Isaac, which damages enemies.",
                "+0.25 Speed. Running into enemies while at a high speed will deal 18 points of damage. Does not prevent contact damage.",
                "Orbiting familiar that blocks enemy shots and deals damage to enemies. If collected while already having one, makes the familiar evolve. Only drops from Horsemen. Similar to Cube of Meat.",
                "Adds a chance to shoot slowing tears and the character leaves a trail of slowing creep behind as he moves.",
                "Activated Items can be overcharged to allow for an additional use.",
                "Increases speed by 0.3",
                "When hit, summons a white attack fly similar to Distant Admiration for the current room.",
                "Increases the size and damage of familiars.",
                "Spawns a familiar that flies around the room in a manner similar to the Boom Fly and explodes on contact with an enemy. Respawns after ten seconds.",
                "Spawns a large orbital familiar that blocks enemy projectiles and deals slight contact damage to enemies.",
                "When taking damage, Isaac farts, causing poison damage to all enemies in range.",
                "Prevents Curses. Grants one black heart. If obtained on a floor with a Curse, it will remove the Curse.",
                "Grants the player one red heart container, one soul heart, and one black heart.",
                "Grants 1 heart container and restores 5 red hearts.",
                "Increases damage by 1 and range by 5 for tears fired from the left eye.",
                "Increases Damage by 1, and turns Isaac's tears into blood tears.",
                "Increases damage as Isaac receives damage. Damage increase stays for the whole floor.",
                "Grants 1 heart container and increases tears, but decreases shot speed.",
                "Shows secret and super secret room locations on the map.",
                "Spawns a familiar that charges forward when shooting tears, explodes upon contact with an enemy and poisons them. Respawns after few seconds.",
                "Gives 5 bombs and grants all bombs poison effect.",
                "Gives Isaac 5 Bombs, and causes all dropped bombs to home towards the closest enemy.",
                "Adds 3 Heart Containers.",
                "All standard bomb pickups become 1+1 Free bombs.",
                "Isaac is followed by a small bag that drops a Bomb, 1+1 Free, or a Troll Bomb every 3 rooms.",
                "Gives 10 bombs.",
                "Spawns 1 of each (non-collectible) item: 1 coin, 1 key, 1 bomb, 1 heart, 1 card, 1 pill, 1 trinket.",
                "Adds 1 Heart Container.",
                "Tears are replaced by a laser beam that pierces through all enemies and obstacles in its path and deals high damage. Can only be fired after a short charge-up period.",
                "Chance upon entering a room to slow down or speed up every enemy and their attacks. The chance to slow enemies is quite higher than the chance to speed them up.",
                "Follows Isaac around shooting normal tears.",
                "Grants two empty heart containers and heals Isaac by half a heart, but decreases speed by 1.",
                "A portable Beggar who follows Isaac, picks up coins for himself, and occasionally drops a Pickup after collecting a coin. Does not spawn Collectibles.",
                "Gives +5 Bombs and makes all bombs <b>Butt Bombs</b> that fill the room with gas, damaging and Confusing all enemies.",
                "Increases speed and reduces character size. Also gives a random pill.",
                "Spawns a familiar that floats slowly around the room on a zig-zag pattern similar to The Peeper and shoots normal tears in the same direction as Isaac.",
                "Adds 3 soul hearts. Grants The Wafer effect for the current room upon taking damage.",
                "All stats up.",
                "Increases Shot Speed and damage.",
                "Grants a chance to trigger the Book Of Shadows effect upon taking damage, creating a shield that nullifies all types of damage for 7 seconds.",
                "Adds 3 Black Hearts and increases Damage by 1.",
                "Increases damage, but also increases the chance of Champion enemies appearing.",
                "Heals the character for half of a red heart for every 13 monsters killed.",
                "Tears fired from left eye do increased damage.",
                "Grants charged tears that deal greater damage when fully charged.",
                "Adds a chance to shoot poison tears, dealing damage over time when inflicted.",
                "Reveals all special rooms (except secret rooms of any kind).",
                "Doubles the number of item pickups and chests spawned after clearing a room or performing some other triggering action (such as using a Blood Donation Machine).",
                "Increases Tears by 0.16 and reduces Range by 10. When tears hit an object or deplete their range, they spawn 4 smaller tears. Distance traveled and size/damage of the child tears is determined by Range and Damage of Isaac, respectively.",
                "Increases damage by 0.5, and multiplies it by 1.5x.",
                "Orbiting familiar that blocks enemy shots and deals damage to enemies. If collected while already having one, makes the familiar evolve. Only drops from Horsemen. Similar to Ball of Bandages.",
                "Grants Isaac piercing tears that travel through enemies (but not obstacles) instead of breaking on impact with them.",
                "Grants charged tears that can be fired in a tight burst of four. Getting hit while charging will teleport Isaac into another room.",
                "Daddy Long Legs' shadow follows Isaac and stomps on enemies.",
                "Spawns a familiar that follows Isaac around and collects red hearts. For every one-and-a-half red hearts collected, Dark Bum will generate one soul heart, one hostile Spider or one friendly Blue Spider.",
                "Increases Damage by 1 and adds a chance to shoot fear tears.",
                "Spawns a flying familiar for the current room that chases enemies whenever Isaac takes damage.",
                "Sets the amount of red heart containers to 1, but gives Isaac 9 extra lives. After dying, Isaac is teleported to the last safe room. New heart containers can be obtained after picking up this item, but after each death, the number of heart containers is set to 1 again.",
                "Grants spectral tears and flight.",
                "Grants piercing and spectral tears. Increases tear size (without increasing damage) while greatly reducing range and shot speed.",
                "Increases Damage by 1.5, reduces Tears by 0.3 and increases tear size. Grants piercing tears. Tears are replaced by Death's scythes, which is a cosmetic effct only.",
                "Follows Isaac and automatically fires at enemies in its reach.",
                "Adds 1 Heart Container.",
                "Adds 1 Heart Container.",
                "A red attack fly circles further out than the Halo Of Flies/Pretty Flies, but closer than Forever Alone. Deals more damage than Forever Alone.",
                "Gives Isaac 99 coins. Can be found multiple times in a single playthrough.",
                "Tears are replaced by bombs that benefit from bomb-enhancing effects and slide a fixed range after being fired.",
                "Spawns a familiar that follows Isaac around and blocks enemy projectiles. Upon blocking a shot it has a chance of triggering The Necronomicon effect.",
                "Gives \"Turdy Touch\" Effect. Enemies that touch Isaac are changed into Poop.",
                "Isaac's tears are replaced with guided missiles, like those used by the Doctor's Remote.",
                "Doubles damage, halves tears stat, and greatly reduces shot speed.",
                "Randomly increases and decreases some of the character's stats. There will always be at least one stat increase and one decrease and the same stats can be increased/decreased multiple times.",
                "Has a chance to drop a random pickup when Isaac takes damage.",
                "Grants flight and one Eternal Heart.",
                "Grants flaming tears that deal burning damage over time. Tears have a chance to explode on impact with an enemy, which creates a fire at the location of the explosion.",
                "Spawns a blue attack fly that orbits a long distance from Isaac.",
                "Suture becomes attached to Isaac, and does touch damage to enemies within its attacking range.",
                "Spawns a familiar that follows Isaac around and fires spectral tears.",
                "Has a chance of spawning a soul heart or black heart when taking damage. Enemies have a chance to drop a Half Red Heart after being killed.",
                "After standing still and not shooting for a short time, Isaac turns invincible until he moves or shoots.",
                "A Devil Room /Angel Room Door will always spawn after every boss fight, excluding the first floor and floors after Utero II/Womb II.",
                "Increases damage and range while reducing tears and shot speed. Grants homing tears and tears gain a damaging halo.",
                "Increase Damage by 1 and Speed by 0.4.",
                "Spawns an orbital familiar that blocks enemy projectiles, deals contact damage to enemies and increases the speed of all orbital familiars.",
                "Isaac's head is removed from his body and floats around him. Increases Damage by 1 and Tears by 0.16.",
                "50% chance to respawn with 1/2 heart after death.",
                "Loosely follows behind Isaac. Can be swung like a flail by rapidly spinning Isaac in a circle. Grows bigger by killing enemies.",
                "Increases chance of gold chests and normal chests.",
                "When Isaac is hit, 1 point of an item's charge is filled.",
                "Grants one Heart Container,+0.3 Damage, +0.2 Tears, +0.25 Range, +0.3 Speed and +0.5 Tear Height",
                "Spawns two pretty fly familiars that block enemy shots and deal contact damage to enemies.",
                "Spawns a familiar that follows Isaac around and fires two tears at once in a V-pattern.",
                "Familiar that follows Isaac, leaving blood creep on the ground.",
                "Increases the size of blue spiders and flies and doubles their damages.",
                "Grants flight and one heart container.",
                "Automatically negates first taken damage in every room.",
                "When Isaac receives damage, the bottle breaks and a puddle of blue Creep forms, which damages non-flying enemies, similar to Lemon Mishap. The bottle is reformed upon entering a different room.",
                "Grants 5 bombs and applies burning blast effect.",
                "Gives one extra pickup (1+1 Free version) of Red Hearts, pennies, bombs and Keys. Does not work with blue, black and half red hearts, nickels and dimes.",
                "A brown/grey mask. Damage reduction. Can block projectiles on the side Isaac is facing.",
                "1-3 Blue Flies randomly spawn every time Isaac gets hit.",
                "Grants an infestation shot that spawns allied blue spiders from killed enemies.",
                "Grants a triple shot but greatly decreases tears.",
                "Replaces tears with explosive and poisoning projectiles fired in an arc from the mouth.",
                "Increases damage by 0.3 and adds a chance to shoot concussive tears, causing enemies to walk around randomly.",
                "Isaac himself is now immune to all damage, and a heart familiar appears and follows Isaac. If the heart is hurt, Isaac is hurt.",
                "Increases Damage and Range.",
                "Adds an extra life; upon death, it respawns Isaac as Judas' Shadow with only two black hearts.",
                "A Familiar that follows behind Isaac. It drips a trail of creep, which slows enemies, and spawns 1-2 Blue Spiders after each room.",
                "Combined with Key Piece 2, unlocks the golden gate in the starting room of The Chest and Dark Room to fight Mega Satan.",
                "Combined with Key Piece 1, unlocks the golden gate in the starting room of The Chest and Dark Room to fight Mega Satan.",
                "Allows Isaac to walk across gaps one square across by automatically placing a ladder between the two walkable sections.",
                "Increases Luck by 1, grants 1 Soul Heart and spawns 2 Keys.",
                "Upon dying, resurrect with one heart container and Anemic item.",
                "Spawns a friendly familiar leech on the ground that hunts down enemies and heals you for half a heart each time it eats one.",
                "Allows you to crush rocks when you walk over them",
                "Gives 6 coins, 6 bombs and 6 keys and balances out all attributes.",
                "A Familiar that shoots a small Brimstone beam. Must charge like the Brimstone Item before shooting.",
                "A familiar that damages enemies by chasing them as well as inducing the fear effect.",
                "Gives Isaac a random Pill and add a slot pill",
                "A Familiar who will drop a half Heart every 2 rooms.",
                "A Familiar that charges forward and deals touch damage to any enemies in her path. Will attack when the Isaac attacks with a moderate cooldown time before she can attack again.",
                "Spawns a familiar that follows Isaac around and fires slowing tears.",
                "Spawns a familiar that follows Isaac around and fires homing tears.",
                "Gives a random chance for projectiles to fire in all 4 cardinal directions.",
                "Grants flight.",
                "Every tear has a small shield which will allow it to block one enemy projectile.",
                "+1 Luck. Increases chance of winning Shell Game Beggar. (Independent of luck stat)",
                "Instead of firing tears, Isaac controls one floating tear that hover over obstacles. This tear deals constant damage when held in place over an enemy.",
                "The more distance tears travel, the more damage they will do.",
                "Adds 1 Heart Container.",
                "Gives one heart container and doubles the healing provided by red hearts.",
                "Increases Shot Speed, and drops a Tarot Card when picked up.",
                "Increases all stats and enlargens Isaac",
                "Increases luck and HP by 1.",
                "Pulls Pick Ups towards Isaac.",
                "Increases Damage and Speed, plus adds one Soul Heart.",
                "Grants Isaac 1 Black Heart and 3 bombs. Can also give troll bombs.",
                "Adds a heart container, and increases damage.",
                "Enemies that touch you are stunned and turn gold. Any enemy killed while in this state will drop a coin.",
                "Grants the combined effects of the Blue Map, Treasure Map and The Compass, revealing the floor layout and all special rooms, including Secret Rooms and Super Secret Rooms.",
                "Increases Speed and Range.",
                "Gives 1 black heart. Chance to inflict The Necronomicon effect upon taking damage.",
                "Randomizes all passive items upon pickup and at the start of each succeeding floor.",
                "Grants a chance of converting any red hearts pickups into soul hearts instead.",
                "Spawns 4 random Pills around Isaac.",
                "Adds a chance to shoot petrifying tears, which stop enemies in place and prevent them from moving or attacking.",
                "Allows Isaac to fire tears from the back of his head.",
                "Tears have a chance to charm enemies.",
                "Increases range.",
                "Spawns 2 keys. Generates additional pickups from chests.",
                "Isaac's tears are replaced by a knife that pierces enemies, can travel through obstacles, and can hurt enemies while Isaac is holding it. Holding down the fire button before firing increases its range and power.",
                "Increases range.",
                "Adds a chance to shoot fear tears and increases Tears by 0.16.",
                "Allows Isaac to hold 1 additional trinket.",
                "Increases range.",
                "Randomly spawn up to 5 blue spiders when firing tears",
                "Increases damage by 0.04 for every coin Isaac has up to +3.96 damage at 99 coins.",
                "Summons a Familiar that copies the tears of another familiar following Isaac. If no other familiars are present, Mongo Baby will fire normal tears.",
                "Increases damage and grants a charged shot that fires multiple tears in the same fashion as Monstro.",
                "Gives Isaac 5 bombs, and makes all dropped bombs larger, which have an increased blast radius and increased damage.",
                "Grants an infestation shot with a 1/6 chance of spawning allied blue flies when tears hit an enemy.",
                "Grants a quadruple shot but decreases tears.",
                "Gives Isaac's tears a boomerang effect, and sets range to default.",
                "Tears leave a small, short lasting pool of creep on impact or when their range is depleted.",
                "Spawns a familiar that follows Isaac around and has a chance to drop a heart, coin, bomb, or key after clearing a room.",
                "Tears range is heavily decreased, but the fire rate is greatly increased.",
                "Grants an empty heart container. Increases damage, range and shot height while reducing speed.",
                "Increases Tears and Speed while reducing Damage.",
                "Adds one empty heart container. Whenever Isaac takes damage there's a chance that a Red Heart may drop.",
                "Grants spectral tears that travel through obstacles (but not enemies) instead of breaking on impact with them.",
                "Increases damage by 0.5, tears by 0.7 and grants two soul hearts upon pickup.",
                "Spawns several coins around Isaac.",
                "Makes the Isaac's tears split in two when they hit something.",
                "Spawns a familiar that floats slowly around the room on a zig-zag pattern similar to boom flies damaging enemies it passes through.",
                "Increases Damage and increases chances of the Devil Room appearing.",
                "Converts all bad pills into good pills, spawns one pill pickup and restores health. Identifies all pills upon pickup.",
                "Increases tears, adds knock-back shots and increases tear size.",
                "Gives 3 pennies on pick-up. Every time Isaac is damaged, he will drop one additional penny.",
                "Regeneration, and increases HP by 1.",
                "Makes Isaac shoot one huge tear. Also reduces Tears to minimum. Damage increased . If tear does more damage than an enemy's life, the tear continues to travel with the extra remaining damage.",
                "Tears start out massive with high damage, and then shrink down and become weaker over a short range.",
                "Spawns a Mulligan Familiar that will wander the room randomly. Enemies will attack the Mulligan if it's closer.",
                "Adds 99 bombs.",
                "Isaac heals 1 heart instead of taking damage by a explosive blast from source. Adds 5 bombs.",
                "Gives you 25 cents.",
                "Spawns a familiar that follows Isaac around and fires rainbow tears.",
                "Increases available Heart Containers by 2 and completely restores health.",
                "Isaac is followed by a small blue cross that will drop a Soul Heart every 5 rooms.",
                "Follows Isaac around, shooting enemies with an eye laser similar to Technology.",
                "Fires lasers at any enemy in its line of sight and moves based onthe direction Isaac is firing tears",
                "Increases speed and range.",
                "Adds 3 Soul Hearts and increases the chance for The Bible to appear in the Shop.",
                "A familiar that spawns Blue Flies.",
                "Adds one heart container.",
                "Tears bounce off walls and obstacles (including enemies).",
                "Isaac is followed by a small bag that drops a coin every 2 rooms. Usually a penny, sometimes a nickel.",
                "Increases damage and range while reducing shot speed and grants homing tears. Replenishes all Red Hearts and gives one Soul Heart upon pickup.",
                "Dagger orbits Isaac, dealing very high damage.",
                "+5 Bombs. Upon exploding, bombs shoot 8 tears off in every direction, similar to Tammy's Head. The tears are affected by any tear modifiers Isaac has on his own tears.",
                "Increases Tears by 0.7.",
                "Increases range and shot speed, while adding 1 Black Heart.",
                "Increases speed by +0.2 and grants piercing tears.",
                "Pull a chain and ball behind you that will damage enemies on contact and is able to break stones.",
                "Once per room, when Isaac is reduced to his last half red Heart, the aura around his head temporarily vanishes and he is granted one Soul Heart.",
                "Grants poison tears, which deal damage over time when inflicted.",
                "Tears and shot speed up.",
                "Using an activated item while it's not charged will charge it and Sharp Plug does 2 full heart damage to Isaac",
                "Wanders about the room, occasionally spawning blue Spiders.",
                "A Familiar that follows Isaac around shooting blood tears.",
                "All types of fly except Boom Fly and Red Boom Fly become passive and slowly move towards Isaac. Does not prevent contact damage.",
                "Sets your key count to the maximum of 99.",
                "Increases damage by 1.",
                "After Isaac takes damage, this fly will deal continuous touch damage to whatever enemy caused the damage until it is dead. The fly will then systematically attack 1 enemy at a time until the room is cleared.",
                "Increases all stats.",
                "Adds 1 Heart Container.",
                "Tears shrink and do much less damage, but fire in very rapid succession.",
                "Grants two Soul Hearts. Isaac now repels enemy projectiles.",
                "Speed and Shot Speed increase.",
                "Reveals type of adjacent rooms, including location for secret rooms and super secret rooms.",
                "Adds a chance to shoot slowing tears, reducing speed of enemy movement and any projectile fired by them.",
                "When hit, spawn up to 2 Blue Spider.",
                "Grants spectral tears and flight.",
                "Grants Isaac homing tears.",
                "Increases tears by 0.4, and spawns 2 Soul Hearts pickups.",
                "Isaac can hold 2 cards at once and all pills are replaced by cards.",
                "Reduces all Shop prices by 50%, rounded down when an item, rounded up when a pickup.",
                "Adds one filled Heart Container and increases Shot Speed.",
                "Increases Damage by 1.",
                "Increases damages, and adds 1 heart container.",
                "Automatically inflicts slow to all enemies in every room.",
                "Pick Ups, Chests and Monsters are magnetically attracted to your tears.",
                "Grants one Heart Container and gives 2 Soul Hearts.",
                "Increases damage and range.",
                "Speed down, gains speed while in a room with enemies until gaining My Little Unicorn effect for a few seconds.",
                "Grants a unlimited range piercing laser with random rate of fire that does not replace tears. The laser might occasionally fire with the effect of a random item or trinket, such as Hook Worm, Spoon Bender or Tiny Planet.",
                "Replaces tears with a piercing laser with unlimited range.",
                "Decreases damage and replaces right eye tears with a unlimited range, piercing laser which fires continuously.",
                "Range up and makes shot tears revolve around Isaac until they drop.",
                "If the character has half a red heart or no red hearts after taking damage, it triggers The Necronomicon effect, damaging all enemies in the room. Also allows entrance into the Dark Room.",
                "If the character has half a red heart or no red hearts after taking damage, it triggers the Book Of Shadows effect, creating a shield that nullifies all types of damage for 7 seconds. Also allows entrance into The Chest.",
                "There will be 2 items available to chose from after defeating a boss. Choosing 1 item causes the other to disappear. Shop item.",
                "Destroys rocks upon contact with Isaac. Adds one heart, and Lowers Speed.",
                "Increases tears and shot speed.",
                "Tears + Shot speed up.",
                "Adds a chance to shoot a tooth instead of a tear, which deals greater damage than regular tears.",
                "Grants flight.",
                "Reveals all rooms for every floor. However, it does not reveal icons or secret rooms.",
                "Isaac gains a shield that will protect him from enemy shots.",
                "All sources of damage that would cause one heart loss are reduced to half heart instead.",
                "Increases damage and speed whenever the character health is half red heart or less (one red heart for Eve).",
                "Increases Tears by 0.7.",
                "Increases speed by 0.3.",
                "Grants a chance to trigger the Book Of Shadows effect upon taking damage, creating a shield that nullifies all types of damage for 7 seconds. Also converts bad pills into good pills.",
                "Inflicts poison to enemies who make contact with Isaac.",
                "Reveals and opens all Secret Room and Super Secret Room entrances.",
        };

        final String images[] = new String[] {
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/52/Less_Than_Three_Icon.png?version=62fecd18a85499e5dbbf7fef1d7b0269",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/83/Blue_Baby%27s_Only_Friend_Icon.png?version=68c9eb6842db4cac4404f1c04b999a32",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/90/1up%21_Icon.png?version=d4822d90a5afcb0e9c1d6ec7ca987f45",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a4/20_20_Icon.png?version=379a7239eb11e732b1c8282ab76fae52",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/58/3_Dollar_Bill_Icon.png?version=2b80e1a2b6ee0d79d7c86a6e33d701ee",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/56/9_Volt_Icon.png?version=be9b9835369bcb14597b7f8feef5197f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1a/Abaddon_Icon.png?version=ebd60c85659db5571a8c7d9f93fbc414",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e9/Abel_Icon.png?version=8ed9e3d290405f1f2c0810d8bc695a3a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5f/Anemic_Icon.png?version=cf1e89426512f6eef7dfe923a530a7ad",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/45/Ankh_Icon.png?version=3c8195123f910f0d546ba33ca4780294",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bc/Anti-Gravity_Icon.png?version=131a13b66ae9bea62d0ef8a67f9850d8",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/59/Aquarius_Icon.png?version=3db793c13d5236e656a0d3d1329070f6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/19/Aries_Icon.png?version=c977abdd5e331f339e1bcafb35691c62",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7d/Ball_Of_Bandages_Icon.png?version=45e86305f76f23b2bc96c7040bc24c05",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5c/Ball_Of_Tar_Icon.png?version=4f0effa0d986235199568976f0d2caa6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/8b/The_Battery_Icon.png?version=686e5abfa19bc7191a092c8718fb819b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/50/The_Belt_Icon.png?version=1561078fae8986cee99d354fd27d7101",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/ef/Best_Bud_Icon.png?version=a35c9fb1e5a6bc94266bc8a251dd7327",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/ae/BFFS%21_Icon.png?version=60647fbbc40164135bbf4c2b53d48921",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/42/BBF_Icon.png?version=b241ca5a2cb2dff1544cd8a24e316fb3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9d/Big_Fan_Icon.png?version=03f8f137eae9a1dd9c2e5bdacf7995d4",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/14/The_Black_Bean_Icon.png?version=bbd80554ab6c455957fb104b00e61270",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b9/Black_Candle_Icon.png?version=5295b8cfcb46203c437a79d08913ed96",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/ff/Black_Lotus_Icon.png?version=86cdc402732e3d89fbf10e960b5a7567",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/29/Blood_Bag_Icon.png?version=de74fab50662a0cda446db2e4ce3343b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/94/Blood_Clot_Icon.png?version=6033ef1a8d1775c5f17e0dd19f152ac4",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/2f/Blood_Of_The_Martyr_Icon.png?version=f19a1723f07198a9b7e4f12d5df53625",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/da/Bloody_Lust_Icon.png?version=044ad03efbe73bd8f05be4e49cee4192",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/ac/Blue_Cap_Icon.png?version=2e931bbf0c2a74d809e9211a7b42eb37",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/07/Blue_Map_Icon.png?version=da915f94940064bfa6d89aebf11cada9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/47/Bob%27s_Brain_Icon.png?version=1a17c0b4185e377123a122fe2343cf1f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d7/Bob%27s_Curse_Icon.png?version=d61acbf79ba738222be5d872e8d63138",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d3/Bobby-Bomb_Icon.png?version=065bb6e3b4598f08bbd3c0ce561d6e73",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/88/The_Body_Icon.png?version=7bf8e914b51b7f14a76466adf96bb643",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/72/Bogo_Bombs_Icon.png?version=29f1e78d233fe960eaea6f2bf901b253",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e0/Bomb_Bag_Icon.png?version=82b3efbde4a7938e5b0a810f229489d1",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b4/Boom%21_Icon.png?version=ea3cd639663fea9078accf05af4e56ae",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/4f/Box_Icon.png?version=bdb3b9f6478a2d60d952667b2d2e5ea8",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/71/Breakfast_Icon.png?version=3527f7c0b3ee7b37dad1bb65c0a6374b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c8/Brimstone_Icon.png?version=063ba351695ca39e52db54a08dff4c8f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e1/Broken_Watch_Icon.png?version=5f7ac93de39758cdb621d8db736f8b54",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/33/Brother_Bobby_Icon.png?version=406b6d28b4f88533dc6730e332eee8ff",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/96/Bucket_Of_Lard_Icon.png?version=c59c39b68d4a2d34a08a37c88bd99ade",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bf/Bum_Friend_Icon.png?version=ae1b5c49f39129240a753878fbac4e8a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b3/Butt_Bombs_Icon.png?version=f874ea3cdb7ba378bdeaf4d8b56b86d3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/49/Caffeine_Pill_Icon.png?version=41d3c432cbefcb5d0e32a9150ac7e983",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/fc/Cain%27s_Other_Eye_Icon.png?version=e4abe0eb7946264c4a3b64a24f80c8bc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/43/Cancer_Icon.png?version=2bd03d32c7a76b6ff314201c6b193c92",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/37/Capricorn_Icon.png?version=3caab4d0e6547ed7b724d0210893decd",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/59/Cat-O-Nine-Tails_Icon.png?version=373c2e6a7fa38044b51a7d018d60551b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/57/Celtic_Cross_Icon.png?version=0f92c9f60f178c7668254a40e009ae58",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7c/Ceremonial_Robes_Icon.png?version=46e341525c8ad45b62efaebbe8a69295",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/25/Champion_Belt_Icon.png?version=b18acdeddb8b3721fcafc927e4c9d075",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7d/Charm_Of_The_Vampire_Icon.png?version=a11e944ae24c04ff6ddab129f9fbc22e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/ba/Chemical_Peel_Icon.png?version=aa3552849b9cb87e3013a0803a857ebe",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/33/Chocolate_Milk_Icon.png?version=c72d6d225b2f6cd35b6ae2864b51f86c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6b/The_Common_Cold_Icon.png?version=d3952f50f8d6456ac29014dfc4a5046e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/96/The_Compass_Icon.png?version=2ee02b7fde75584c2a0e817a4da30e33",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1b/Contract_From_Below_Icon.png?version=d0a0673c1dd764d0b117ab934bd96091",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/10/Cricket%27s_Body_Icon.png?version=bad2544dd3d30a0425bb52d4a4cfccfd",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/54/Cricket%27s_Head_Icon.png?version=f5722de4b0b0b9546e2f358eaea1ee1c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/cc/Cube_Of_Meat_Icon.png?version=b5795a96a513fdc780cfaa3b6a4886e9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/98/Cupid%27s_Arrow_Icon.png?version=ffb3c0bec7012266e66c7f4d547d3711",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/66/Cursed_Eye_Icon.png?version=af7c524ff26edaec38c37d53fb1dcefd",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/ea/Daddy_Longlegs_Icon.png?version=f5a5f67408df906510cf0a33f5e02ab2",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bf/Dark_Bum_Icon.png?version=53e8dc90924b6370b108ba41a4af7c0b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/85/Dark_Matter_Icon.png?version=2dd1b1deb8de1c9a1e803f0f67731639",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/13/Dead_Bird_Icon.png?version=c31a2e0241f869dcf86a9fd3de9ae559",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/27/Dead_Cat_Icon.png?version=c53a429e8b9066cb19e61182fca3750c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1f/Dead_Dove_Icon.png?version=834322c69ff49b129b6eaaab629b05cf",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/cd/Dead_Onion_Icon.png?version=48b0166f0dd6d0b7ce53aaf75e58d774",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/2c/Death%27s_Touch_Icon.png?version=e8e181e7fac88fe293fcd8a64db06217",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a6/Demon_Baby_Icon.png?version=e17579fd9a8fd495ffabd6cdcb21d911",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/70/Dessert_Icon.png?version=cb95c032d884465a5d19a8835606ba29",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/71/Dinner_Icon.png?version=01a9978a811685b469f9a2b35927d1bf",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/71/Distant_Admiration_Icon.png?version=54ad4d5655312b06d7668ecdd69972c6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/51/A_Dollar_Icon.png?version=fa65780ca2222d37b1a98ba5afc9523d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/78/Dr._Fetus_Icon.png?version=4e50be685366a412675080a99438052e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d5/Dry_Baby_Icon.png?version=de3190fa825153a7867e1e3d23a2b0c7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3b/E_Coli_Icon.png?version=e2a5d3e0a44175f8d7b1f221d766a563",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d0/Epic_Fetus_Icon.png?version=2ff239eac8e20e0cad2076318c8ff83c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/da/Eve%27s_Mascara_Icon.png?version=d96f45b1398dd05c5f7c23e7c83b59b4",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/01/Experimental_Treatment_Icon.png?version=c21d8bf672b8ef2a6b45f954f02a55aa",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/66/Fanny_Pack_Icon.png?version=eec00657104bad73274d559bb9ea7ed9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a8/Fate_Icon.png?version=d0e527fe57c2c40a475de3872fa2aab7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/46/Fire_Mind_Icon.png?version=bdb719000563a2e3bf681d3cc0f23b79",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d5/Forever_Alone_Icon.png?version=5f630ebc994dffc377b7ed7080e6eff7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/thumb/7/73/Gemini_%28Item%29_Icon.png/45px-Gemini_%28Item%29_Icon.png?version=10c5fdd7acb3a8b512d25a440655a11f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f5/Ghost_Baby_Icon.png?version=b8b91d94643544f036a8e0177a71886c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/26/Gimpy_Icon.png?version=7937af8c9fd07829f90b1701b1dac0a5",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/15/Gnawed_Leaf_Icon.png?version=81e2bc63571445d2303f4baab54aacda",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/82/Goat_Head_Icon.png?version=cdab71a0651a6c6cf6661c7b0e2bd486",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3b/Godhead_Icon.png?version=9b260cd02ad76f6f0150dea07e7d0388",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/70/Growth_Hormones_Icon.png?version=190e738e609acf698af2569b2e2942fc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f6/Guardian_Angel_Icon.png?version=d7531d91a883dbe27f65c08601a9b020",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/0a/Guillotine_Icon.png?version=6b505510f45fc4e15711d2917236fe61",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/13/Guppy%27s_Collar_Icon.png?version=8134b36415e497757edffb115d9bb30f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e4/Guppy%27s_Hair_Ball_Icon.png?version=9e09bdd08b395c1bc8b0c893013b8fe0",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1d/Guppy%27s_Tail_Icon.png?version=958d45c5e289f59d291deb70dcb53ebb",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/da/Habit_Icon.png?version=b51203644b0fb7cecf7120cc813ec894",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/20/The_Halo_Icon.png?version=c3eac4d02003ae6430164e31bdabb6f2",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/db/Halo_Of_Flies_Icon.png?version=e40a12d64df869964d0c465a2e256b22",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/db/Harlequin_Baby_Icon.png?version=d9c8c532c8b6cd718814de89d1440876",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7a/Headless_Baby_Icon.png?version=68c5703c073a95e363672e964ccf79d3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3e/Hive_Mind_Icon.png?version=d6994659317089c9f4c0921bc34ce56a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c9/Holy_Grail_Icon.png?version=1dc88b18133ac005932d248d84c57b13",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c7/Holy_Mantle_Icon.png?version=7f10cc08104d42f5acf2873c8277c2fd",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/51/Holy_Water_Icon.png?version=f85fa5bdcba2e444997bb58eb8566329",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/20/Hot_Bombs_Icon.png?version=69d1d11fb0839b5b12617ac173f472e0",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5a/Humbling_Bundle_Icon.png?version=f5f6290b5bdb1522d2a4f3161e32e459",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/fd/Infamy_Icon.png?version=bea6fc50e9114b85d992f796cf7161a2",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6a/Infestation_Icon.png?version=8a1c45b510739f36440f5b0de0a62c10",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/4d/Infestation_2_Icon.png?version=26336468dd59d18064f8846e9865e8fa",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b9/The_Inner_Eye_Icon.png?version=3c7fa03657aedbfdc921cef98beb8a82",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f3/Ipecac_Icon.png?version=d2b9adac3ac11caffb34bea66c3c3a07",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/84/Iron_Bar_Icon.png?version=905f28ee0afbd5418b1ad5c423714851",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/20/Isaac%27s_Heart_Icon.png?version=2a7562bbc9ed7963ab943ed7203b89b3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/98/Jesus_Juice_Icon.png?version=7197398297eb499380c078aba7d97eef",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f5/Judas%27_Shadow_Icon.png?version=4f81c429c91747a94eadc105593acaa5",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/13/Juicy_Sack_Icon.png?version=72c820d46f1cdccf12efd6e43cd5b327",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/28/Key_Piece_1_Icon.png?version=f18d8ca48f5955dbddfd10ba0e318738",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5d/Key_Piece_2_Icon.png?version=86ab22a9596afba4ae33cbaad4fecc00",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/4a/The_Ladder_Icon.png?version=45f3896e560495b694f461e2e3b4aefc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/ca/Latch_Key_Icon.png?version=d37b09831d1eddfd28d694857fecc45e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/cf/Lazarus%27_Rags_Icon.png?version=26473b543102c067dff88729126d156e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/52/Leech_Icon.png?version=4551a4339471a69a8c9802721951b8ed",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3d/Leo_Icon.png?version=0e659372f1aaec56f350d2a4e7037128",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a7/Libra_Icon.png?version=c828e30051862f532294c23d3172a4bf",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b6/Lil%27_Brimstone_Icon.png?version=ff9822627081cc86f639fad2d452e6fa",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e9/Lil%27_Haunt_Icon.png?version=fef9dc3521cc82d37c1ea1948545680d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/88/Little_Baggy_Icon.png?version=0f71e51340b99ff8db0e0cd5679cadec",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1b/Little_C.H.A.D._Icon.png?version=7b43a25902cf50bd02472f42208d893c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/61/Little_Chubby_Icon.png?version=79cff152efca87e35757573a33f56c56",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e8/Little_Gish_Icon.png?version=c744f3a2ca28676328ef8ec84be9a956",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3c/Little_Steven_Icon.png?version=2cd2418021babda6d0a848c2d215d47b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/2c/Loki%27s_Horns_Icon.png?version=01726a8fc3c810f2b729e268638f38b4",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d9/Lord_Of_The_Pit_Icon.png?version=3e33689c8baf0eda3e0a364a8bd9a4e0",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6b/Lost_Contact_Icon.png?version=1d630a0eb4df444344d615d75fb036b6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/8e/Lucky_Foot_Icon.png?version=8d380d8e853f4856cd785021f4b3f500",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/05/The_Ludovico_Technique_Icon.png?version=61c4fac256a01a291ef13eaa9f7dcb6c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a6/A_Lump_Of_Coal_Icon.png?version=e525c06df90539ea1e3fe76b0f49f579",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/66/Lunch_Icon.png?version=a177c18f523188762642bf2b9e52517e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6c/Maggy%27s_Bow_Icon.png?version=f17bb0b24b44a2eac90d8a0bd589e443",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/be/Magic_8_Ball_Icon.png?version=d3667a5623727da8a6b0b5b4fb7b7c7e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/94/Magic_Mushroom_Icon.png?version=309230aa1dfdee7b710b0bbfa803f09c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f2/Magic_Scab_Icon.png?version=d409ed6cbffbbd059ba90b54d5c0a3fe",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/02/Magneto_Icon.png?version=1ef1124752b3d6f4753cdd4d7c5bd83c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b3/The_Mark_Icon.png?version=c22260e3bba4fc1f0f34a2191ba685e3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b4/Match_Book_Icon.png?version=44015c1b2b1a805fc64ef8d7fbd01609",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e0/MEAT%21_Icon.png?version=b2484de6cc24394c520e09e7dcf6fbca",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/42/Midas%27_Touch_Icon.png?version=76174f4b7a2e476d7fd23b7eaee9d583",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f9/The_Mind_Icon.png?version=c6b140324167fb20c0f3ec4bc8805b5a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/02/Mini_Mush_Icon.png?version=e72dbbad85b3ff9cdd0c8a7ba9a98f65",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/17/Missing_Page_2_Icon.png?version=55fe788765938ee6c23e055b4bd20ad1",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b2/Missing_No._Icon.png?version=d5ae0ef600507993862509257b7df636",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3c/Mitre_Icon.png?version=766ac233701c592a85f68594550e3d88",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b1/Mom%27s_Coin_Purse_Icon.png?version=f87b424333c6810a71ba688eed6b29e9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/ad/Mom%27s_Contacts_Icon.png?version=4cbda3b1f0f4004ed84a1b72428bd4fa",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f2/Mom%27s_Eye_Icon.png?version=56210890a11c5a5369a469442ad835b7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/95/Mom%27s_Eyeshadow_Icon.png?version=811ea3fcc1783eac0bab5017d93efd70",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/4c/Mom%27s_Heels_Icon.png?version=9fbcf4fbff80bb0c7b7573faea62b3c4",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/15/Mom%27s_Key_Icon.png?version=436dd7f72270037e543419dcb130684c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bf/Mom%27s_Knife_Icon.png?version=c431b252d9c164a6c3071d153d4f6e44",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/dd/Mom%27s_Lipstick_Icon.png?version=2d9c1110c4d088c85498e6de65f4dce3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/dd/Mom%27s_Perfume_Icon.png?version=823a0d4dd4abadc3868359150e5fdd8c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bf/Mom%27s_Purse_Icon.png?version=dcca4cb6750c4099bff32c8df4430d7b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/94/Mom%27s_Underwear_Icon.png?version=143a06980d05ee54d811fdf5828e5577",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c0/Mom%27s_Wig_Icon.png?version=a55c89e19fb08530b89cc1a5ed936737",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e7/Money_%3D_Power_Icon.png?version=e54c5d139bdb0d7c352a414a352524b6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/ef/Mongo_Baby_Icon.png?version=43ec47e4ec0a5a9faa69ff08d5159f89",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/49/Monstro%27s_Lung_Icon.png?version=34242e97cc9d1311b9a511be86e2190d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/27/Mr._Mega_Icon.png?version=324e8a1894cb4bca77e7eaf867da2985",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1c/The_Mulligan_Icon.png?version=c0a6adac66e2b7d840c352f0d5db2dbb",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6e/Mutant_Spider_Icon.png?version=e701d137b07013d65a0d24a7f9c7bfdc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b7/My_Reflection_Icon.png?version=37d19b503a999014f3d0b2725545908b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3a/Mysterious_Liquid_Icon.png?version=5f51884306aa29ad005c7794ecb158c1",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c0/Mystery_Sack_Icon.png?version=1ea93cf4b827ad16945af9fd645479b7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/43/Number_One_Icon.png?version=6c97eac8df60f573b555b27a933a4703",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/69/Odd_Mushroom_%28Large%29_Icon.png?version=468818999e5a40d4374a36467bfbbcdc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/36/Odd_Mushroom_%28Thin%29_Icon.png?version=9fd66a6de3178623fd874c09fb3f8e01",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/af/Old_Bandage_Icon.png?version=72da82010cb70d513c862b5f15b74026",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e5/Ouija_Board_Icon.png?version=b162e44cec343a58df460131250d9cc8",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3a/The_Pact_Icon.png?version=15d67bb7eefcecbe4ff1bb548fc966c9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/16/Pageant_Boy_Icon.png?version=6657ceebecbf209b3162238127fefc92",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7d/The_Parasite_Icon.png?version=fdbe3165976193d921cfe0a198b3bcde",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/39/The_Peeper_Icon.png?version=719a8f03d857a53e12207270a4cefab7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/95/Pentagram_Icon.png?version=272bc4375969a583db3f983e1d2d98ac",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/ec/PHD_Icon.png?version=cc73a9efe2bc722f4d6defada08d550a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/89/Pisces_Icon.png?version=77f7df71c40cb65e28e724abeed2d1d7",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/0b/Piggy_Bank_Icon.png?version=ac83860de7a8f2ecc728337e80c70d39",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/cc/Placenta_Icon.png?version=0d966e46c2ea17b40e896ed74908d7d3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/2b/Polyphemus_Icon.png?version=92b8820d0a591c24da97670ae304498f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/cb/Proptosis_Icon.png?version=a798e1fc6e54aa6b0a36324dfd749b68",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b4/Punching_Bag_Icon.png?version=faad910c8f38ba7d98ec935cb4f1dee8",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/26/Pyro_Icon.png?version=dacaab69deabb24197184d8b36fa1798",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a0/Pyromaniac_Icon.png?version=d0a6c7508d628b2a81942853ef945f1a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c3/A_Quarter_Icon.png?version=28a64c08d5ae7704c034bd66c06bdf75",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f0/Rainbow_Baby_Icon.png?version=96c86eee96fb62dd08398e608834579d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/29/Raw_Liver_Icon.png?version=f077c0c69eb8e0d1208e58b59e56ebf3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/bb/The_Relic_Icon.png?version=b422a70016d61d2defc60a806ebc2d86",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/77/Robo-Baby_Icon.png?version=2953537f100c65bcc6cac99f92d13dab",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/ce/Robo-Baby_2.0_Icon.png?version=5567861385b1916f76d4527878dfec49",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5a/Roid_Rage_Icon.png?version=920319493f22c266ba11b8d0a1887f8d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9a/Rosary_Icon.png?version=500542180b3687dab3af474a313b25e3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f1/Rotten_Baby_Icon.png?version=fb1ed9f785aff0e08513965f66ab4a8e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d9/Rotten_Meat_Icon.png?version=2dfb49d8757c68527451d21f867f1ce2",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/58/Rubber_Cement_Icon.png?version=a547daf91ee9cbf92bb2507aa527d415",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/20/Sack_Of_Pennies_Icon.png?version=82c43b1e5eaeadcc17accdb057f79a3d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/2c/Sacred_Heart_Icon.png?version=7ee8d809ea16b79be86f8e6d3ec61139",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d6/Sacrificial_Dagger_Icon.png?version=57ad450372bb877e4c665c4da5c2786c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5c/Sad_Bombs_Icon.png?version=72cd7be28c3f794b09946c9b510774b0",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/1a/The_Sad_Onion_Icon.png?version=1e0610ecfd73dbd82fc38aaa10583c0b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/fe/Safety_Pin_Icon.png?version=aaa003863911747ec9c31cd6f333f985",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/55/Sagittarius_Icon.png?version=38ee7bda46bd42e97a93c1556241cf1b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/23/Samson%27s_Chains_Icon.png?version=0ca2b277086f69f40255823af5a9b6e1",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/09/Scapular_Icon.png?version=fc8af537edc86e1bde0eed1ec46223e5",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/69/Scorpio_Icon.png?version=f6bdf5b49cfd5231cbeb32a22c638a1f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/37/Screw_Icon.png?version=916cbeefc47612fca712b2fa32278305",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/08/Sharp_Plug_Icon.png?version=2991ac0cf17109afbd5c77c426d51103",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/80/Sissy_Longlegs_Icon.png?version=227f912358c18f6700021cda81bf15ed",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7e/Sister_Maggy_Icon.png?version=c2e4260743f66d148fd8d0a1b06bc98f",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/81/Skatole_Icon.png?version=427af1ae47cf394a23b844ddb4d4cd16",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/54/Skeleton_Key_Icon.png?version=ebc0cc40455464a96fbba91dee30b7bc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/61/The_Small_Rock_Icon.png?version=8e6fa860bb5a67f22484b31e2e8d3aca",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/da/Smart_Fly_Icon.png?version=7338602675186d2563fc535f274338fb",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/03/SMB_Super_Fan%21_Icon.png?version=fa1576e1c5db1d158ae5e02a59d1d361",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7e/A_Snack_Icon.png?version=9b0baa3e535c170b69349ee6d2fec13c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/39/Soy_Milk_Icon.png?version=301741de8ec349aa067818de1a88fab9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/b/b4/The_Soul_Icon.png?version=52fa16769c5f7917f30ed7755caaa027",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/1/10/Speed_Ball_Icon.png?version=12bc3a5608125ef72edb066c79f73091",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/af/Spelunker_Hat_Icon.png?version=d8d97cc11a3ff14920d139fd9f81faad",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/65/Spider_Bite_Icon.png?version=fcb2f6b3d3601ac53789a296c769e502",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/24/Spider_Baby_Icon.png?version=b9371d182d691809f6e71ca8289e7925",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/93/Spirit_Of_The_Night_Icon.png?version=57641dc6226e2c651433a8d8001f365c",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/ae/Spoon_Bender_Icon.png?version=d280dbfc91790e1313b941f0d07fee96",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/c/c5/Squeezy_Icon.png?version=f40e18f3f0582ba1165d4db613ab5cdc",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/74/Starter_Deck_Icon.png?version=3074efc95aa645c6e6c343cc7c95992d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/87/Steam_Sale_Icon.png?version=adc61fd5fd93373106bef02f9ea6d676",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/53/Stem_Cells_Icon.png?version=ad8622d9d4e32bc500224cfcb6745d89",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/58/Steven_%28Item%29_Icon.png?version=904b4cad129139cb16349a3630c7bb42",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f1/Stigmata_Icon.png?version=d07afb4ca52136b92f78b50376358c24",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/4/40/Stop_Watch_Icon.png?version=904dbe36e0b1f6aee3a1f37a53787498",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e3/Strange_Attractor_Icon.png?version=10dbf290aaf681dd36337c87f4a10316",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/20/Super_Bandage_Icon.png?version=822806adca411caf3ecd068d154b2320",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/6c/Synthoil_Icon.png?version=5dc01a14596792bd31eed195c5d26fae",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/e/e3/Taurus_Icon.png?version=3402a84d06178a309e1e2d1530c0ca67",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9c/Tech.5_Icon.png?version=2e976cd9954242c909465778a11cd12a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/80/Technology_Icon.png?version=e8d8e49d6afa27b1616b76c98003a4d6",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/81/Technology_2_Icon.png?version=7d7e32ffe5ee259a26b62d05d5c09de1",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/3/3f/Tiny_Planet_Icon.png?version=fdee900123ba27cb7527165c877bc3f3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/0a/The_Negative_Icon.png?version=876722a0295f86cd3d71970ff2f5b96d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/f/f4/The_Polaroid_Icon.png?version=f800423ae46b0c40e4fdb6b486e474d9",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/a/a9/There%27s_Options_Icon.png?version=d77e57bdc6711eb7ae055031736e1a5b",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9c/Thunder_Thighs_Icon.png?version=97d79242544203f8278b333672a16f4a",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9b/Toothpicks_Icon.png?version=8128d6d80625d1d7f7c383171750bd7e",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/d/d1/Torn_Photo_Icon.png?version=ae57ea2d645c14914ceba0e0b999c0dd",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/62/Tough_Love_Icon.png?version=d30d6513666915a140751255eea4e1ab",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/62/Transcendence_Icon.png?version=9c7b290c1253b829abb530cab92a54c3",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/5/5c/Treasure_Map_Icon.png?version=bed568ded4d99a39731f6635aa11eaa8",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/2/29/Trinity_Shield_Icon.png?version=f6f9ade7dd32a86d06793f85a6fa2cae",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/97/The_Wafer_Icon.png?version=2a1e8f09656c96d34cf0f64d888c03b0",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/78/Whore_Of_Babylon_Icon.png?version=e895c2d1848a3d0db84ceb8b76688308",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/05/Wire_Coat_Hanger_Icon.png?version=995bdf532a61344666d16ecc24913e87",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/8/83/Wooden_Spoon_Icon.png?version=0786185577a1a254b1ddfc838f310fc2",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/6/66/Virgo_Icon.png?version=e8b848b7f686c0b63726aee72d0d447d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/7/7d/The_Virus_Icon.png?version=a2ec72d1cca1d0b48e36fa341c95481d",
                "http://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/0/00/X-Ray_Vision_Icon.png?version=3cf1725c9149e0803c71c9e469ce75d4",
        };
        SharedPreferences sp= PreferenceManager.getDefaultSharedPreferences(passiveItems.this);
        if(sp.getBoolean("pref_img_key", false)) {
            //Toast.makeText(getApplicationContext(), Boolean.toString(sp.getBoolean("pref_img", true)), Toast.LENGTH_SHORT).show();
            listAdapterItemsPassive adapter=new listAdapterItemsPassive(this, items, images);
            lv.setAdapter(adapter);
        }
        else {
            listAdapterItemsPassive adapter=new listAdapterItemsPassive(this, items, null);
            lv.setAdapter(adapter);
        }
        lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                AlertDialog.Builder builder=new AlertDialog.Builder(passiveItems.this);
                builder.setTitle(items[position]);
                builder.setMessage(effects[position]);
                builder.setCancelable(true);
                builder.setNeutralButton("Ok", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.cancel();
                    }
                });

                AlertDialog alert=builder.create();
                alert.show();
            }
        });

    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_passive_items, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            startSettings();
        }

        return super.onOptionsItemSelected(item);
    }

    public void startSettings() {
        Intent i=new Intent(this, settings.class);
        startActivity(i);
    }
}
